newIssueWelcomeComment: >
  Hello there! ğŸ‘‹ Welcome to FirstTimers! ğŸš€
  
  Thank you and congrats ğŸ‰ for opening your very first issue in this repo. A maintainer will get back to you shortly!
  Join our discord community:- https://discord.com/invite/QHJ6szbdP6


newPRWelcomeComment: >
  Hello there! ğŸ‘‹ Welcome to FirstTimers! ğŸš€
  
  Thank you and congrats ğŸ‰ for opening your first pull request. A maintainer will get back to you shortly!
  Join our discord community:- https://discord.com/invite/QHJ6szbdP6
  

firstPRMergeComment: >
  Congrats on merging your first Pull Request! ğŸ‰ All the best for your amazing open source journey ahead.âš¡ï¸
